### ISSUE TITLE
Custom Sass won't show on the local server

### ISSUE THREAD

**Issue by maya** [uswds/uswds-sandbox#28]
Any custom Sass is not showing up on the live server. Though it is compiling correctly into `styles.css`

Also, seeing this error:

```
[2019-11-12 13:40:24] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:18
	/Users/mayabenari/.rubies/ruby-2.6.2/lib/ruby/2.6.0/webrick/httpserver.rb:82:in `eof?'
	/Users/mayabenari/.rubies/ruby-2.6.2/lib/ruby/2.6.0/webrick/httpserver.rb:82:in `run'
	/Users/mayabenari/.rubies/ruby-2.6.2/lib/ruby/2.6.0/webrick/server.rb:307:in `block in start_thread'
[2019-11-12 13:40:24] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:19
	/Users/mayabenari/.rubies/ruby-2.6.2/lib/ruby/2.6.0/webrick/httpserver.rb:82:in `eof?'
	/Users/mayabenari/.rubies/ruby-2.6.2/lib/ruby/2.6.0/webrick/httpserver.rb:82:in `run'
	/Users/mayabenari/.rubies/ruby-2.6.2/lib/ruby/2.6.0/webrick/server.rb:307:in `block in start_thread'
```

**Comment by maya** [comment]
Looks like it was Chrome caching that was the issue, and once cache was disabled, Sass loaded properly.

**Comment by maya** [comment]
You'll want to add `?{{site.time | date: '%s%N'}}` to the CSS file path in order to bust the cache: https://ultimatecourses.com/blog/cache-busting-jekyll-github-pages
